### ISSUE TITLE
Querying by multiple tag filters

### ISSUE THREAD

**Issue by alexgleason** [mikedilger/relay-tester#2]
Implementing queries with multiple tag filters is actually trickier than I thought and I've messed it up a few times. Would be good to test this.

Example query:

```js
  [{
    kinds: [30383],
    authors: ['db0e60d10b9555a39050c258d460c5c461f6d18f467aa9f62de1a728b8a891a4'],
    '#k': ['3036'],
    '#p': ['0461fcbecc4c3374439932d6b8f11269ccdb7cc973ad7a50ae362db135a474dd'],
    '#n': ['approved'],
    limit: 20,
  }]
```

It would just test that the results match the filters.

**Comment by mikedilger** [comment]
Ok it's been added to master branch.  I also fixed several bugs and now actually test if all the matching events were returned (as well as if all returned events match).

The tester is sorta usable already but I only have about half of the tests that I have imagined, and each new test seems to break the idioms I've constructed, with each idiom break being more significant of a refactor than the last one.
