### ISSUE TITLE
Cannot parse nsec

### ISSUE THREAD

**Issue by bezysoftware** [mikedilger/relay-tester#5]
I keep getting this error even for nsec generated by the included tool:

`Error: NostrTypes(Bech32Decode(Parse(Char(InvalidChar('b')))))`

Can you help?

**Comment by mikedilger** [comment]
Make sure the nsec doesn't have the letter 'b' in it, because that is invalid for bech32, and the error message appears to think it has a 'b' in it.

Make sure you are calling it like:

```
$ relay-tester <relay_url> <nsec1> <nsec2>
```

Make sure you aren't calling it with the hex keys (which will have 'b' characters)

**Comment by bezysoftware** [comment]
Silly me, I didn't realize the output of `generate-keypair` was 2 strings - nsec and its hex version. I thought it was a single nsec wrongly formatted 😢

**Comment by mikedilger** [comment]
Ah... I see that now.  Looks like it wraps or something.  Maybe I should change that.
